// 中文汉字转拼音库 - 覆盖常见组织名称、地名、常用字

const PINYIN_MAP = {
  // === 常见组织名称用字 ===
  '大': 'da', '学': 'xue', '中': 'zhong', '小': 'xiao', '国': 'guo',
  '公': 'gong', '司': 'si', '集': 'ji', '团': 'tuan', '有': 'you',
  '限': 'xian', '责': 'ze', '任': 'ren', '股': 'gu', '份': 'fen',
  '企': 'qi', '业': 'ye', '银': 'yin', '行': 'hang', '医': 'yi',
  '院': 'yuan', '政': 'zheng', '府': 'fu', '局': 'ju', '部': 'bu',
  '委': 'wei', '会': 'hui', '省': 'sheng', '市': 'shi', '区': 'qu',
  '县': 'xian', '镇': 'zhen', '乡': 'xiang', '村': 'cun', '街': 'jie',
  '道': 'dao', '路': 'lu', '社': 'she', '保': 'bao', '税': 'shui',
  '务': 'wu', '财': 'cai', '科': 'ke', '技': 'ji', '信': 'xin',
  '息': 'xi', '网': 'wang', '络': 'luo', '数': 'shu', '据': 'ju',
  '云': 'yun', '计': 'ji', '算': 'suan', '软': 'ruan', '件': 'jian',
  '开': 'kai', '发': 'fa', '系': 'xi', '统': 'tong', '平': 'ping',
  '台': 'tai', '服': 'fu', '电': 'dian', '子': 'zi', '商': 'shang',
  '品': 'pin', '贸': 'mao', '物': 'wu', '流': 'liu', '通': 'tong',
  '讯': 'xun', '移': 'yi', '联': 'lian', '广': 'guang', '播': 'bo',
  '视': 'shi', '影': 'ying', '传': 'chuan', '媒': 'mei', '体': 'ti',
  '文': 'wen', '化': 'hua', '教': 'jiao', '育': 'yu', '研': 'yan',
  '究': 'jiu', '设': 'she', '院': 'yuan', '所': 'suo', '中': 'zhong',
  '心': 'xin', '总': 'zong', '分': 'fen', '支': 'zhi', '办': 'ban',
  '处': 'chu', '站': 'zhan', '点': 'dian', '港': 'gang', '口': 'kou',
  '海': 'hai', '关': 'guan', '检': 'jian', '疫': 'yi', '边': 'bian',
  '防': 'fang', '消': 'xiao', '安': 'an', '全': 'quan', '监': 'jian',
  '管': 'guan', '理': 'li', '控': 'kong', '制': 'zhi', '中': 'zhong',

  // === 高校常见用字 ===
  '师': 'shi', '范': 'fan', '工': 'gong', '农': 'nong', '林': 'lin',
  '医': 'yi', '药': 'yao', '法': 'fa', '经': 'jing', '济': 'ji',
  '财': 'cai', '贸': 'mao', '外': 'wai', '语': 'yu', '艺': 'yi',
  '术': 'shu', '美': 'mei', '音': 'yin', '乐': 'yue', '体': 'ti',
  '育': 'yu', '理': 'li', '化': 'hua', '生': 'sheng', '物': 'wu',
  '地': 'di', '质': 'zhi', '矿': 'kuang', '石': 'shi', '油': 'you',
  '航': 'hang', '空': 'kong', '天': 'tian', '海': 'hai', '洋': 'yang',
  '交': 'jiao', '铁': 'tie', '邮': 'you', '电': 'dian', '建': 'jian',
  '筑': 'zhu', '水': 'shui', '利': 'li', '力': 'li', '能': 'neng',
  '源': 'yuan', '环': 'huan', '境': 'jing', '城': 'cheng', '规': 'gui',
  '划': 'hua', '园': 'yuan', '林': 'lin', '农': 'nong', '牧': 'mu',
  '渔': 'yu',

  // === 省份简称 & 地名 ===
  '京': 'jing', '津': 'jin', '冀': 'ji', '晋': 'jin', '蒙': 'meng',
  '辽': 'liao', '吉': 'ji', '黑': 'hei', '沪': 'hu', '苏': 'su',
  '浙': 'zhe', '皖': 'wan', '闽': 'min', '赣': 'gan', '鲁': 'lu',
  '豫': 'yu', '鄂': 'e', '湘': 'xiang', '粤': 'yue', '桂': 'gui',
  '琼': 'qiong', '渝': 'yu', '川': 'chuan', '黔': 'qian', '滇': 'dian',
  '藏': 'zang', '陕': 'shan', '甘': 'gan', '青': 'qing', '宁': 'ning',
  '新': 'xin', '台': 'tai', '港': 'gang', '澳': 'ao',
  // 常见城市名用字
  '北': 'bei', '上': 'shang', '深': 'shen', '圳': 'zhen', '广': 'guang',
  '州': 'zhou', '杭': 'hang', '南': 'nan', '武': 'wu', '汉': 'han',
  '成': 'cheng', '都': 'du', '重': 'chong', '庆': 'qing', '西': 'xi',
  '郑': 'zheng', '济': 'ji', '青': 'qing', '岛': 'dao', '大': 'da',
  '连': 'lian', '沈': 'shen', '阳': 'yang', '哈': 'ha', '尔': 'er',
  '滨': 'bin', '长': 'chang', '春': 'chun', '合': 'he', '肥': 'fei',
  '南': 'nan', '昌': 'chang', '福': 'fu', '厦': 'xia', '门': 'men',
  '兰': 'lan', '银': 'yin', '呼': 'hu', '和': 'he', '浩': 'hao',
  '特': 'te', '乌': 'wu', '鲁': 'lu', '木': 'mu', '齐': 'qi',
  '拉': 'la', '萨': 'sa', '贵': 'gui', '昆': 'kun', '明': 'ming',
  '温': 'wen', '宁': 'ning', '波': 'bo', '苏': 'su', '无': 'wu',
  '锡': 'xi', '常': 'chang', '徐': 'xu', '淄': 'zi', '博': 'bo',
  '烟': 'yan', '台': 'tai', '潍': 'wei', '坊': 'fang', '临': 'lin',
  '沂': 'yi', '日': 'ri', '照': 'zhao', '德': 'de', '聊': 'liao',
  '菏': 'he', '泽': 'ze', '泰': 'tai', '莱': 'lai', '芜': 'wu',
  '枣': 'zao', '庄': 'zhuang', '东': 'dong', '营': 'ying', '滨': 'bin',
  '威': 'wei', '绍': 'shao', '兴': 'xing', '嘉': 'jia', '金': 'jin',
  '华': 'hua', '义': 'yi', '舟': 'zhou', '黄': 'huang', '冈': 'gang',
  '宜': 'yi', '昌': 'chang', '荆': 'jing', '株': 'zhu', '湘': 'xiang',
  '潭': 'tan', '衡': 'heng', '岳': 'yue', '洞': 'dong', '庭': 'ting',
  '珠': 'zhu', '三': 'san', '亚': 'ya', '桂': 'gui', '柳': 'liu',
  '梧': 'wu', '北': 'bei', '钦': 'qin', '玉': 'yu',

  // === 常见姓氏/名字用字 ===
  '李': 'li', '王': 'wang', '张': 'zhang', '刘': 'liu', '陈': 'chen',
  '杨': 'yang', '赵': 'zhao', '周': 'zhou', '吴': 'wu', '孙': 'sun',
  '马': 'ma', '朱': 'zhu', '胡': 'hu', '郭': 'guo', '何': 'he',
  '高': 'gao', '罗': 'luo', '郑': 'zheng', '梁': 'liang', '谢': 'xie',
  '宋': 'song', '唐': 'tang', '许': 'xu', '邓': 'deng', '冯': 'feng',
  '韩': 'han', '曹': 'cao', '曾': 'zeng', '彭': 'peng', '肖': 'xiao',
  '田': 'tian', '董': 'dong', '潘': 'pan', '袁': 'yuan', '蔡': 'cai',
  '蒋': 'jiang', '余': 'yu', '于': 'yu', '杜': 'du', '叶': 'ye',
  '程': 'cheng', '苏': 'su', '魏': 'wei', '吕': 'lv', '丁': 'ding',
  '任': 'ren', '沈': 'shen', '姚': 'yao', '卢': 'lu', '姜': 'jiang',
  '崔': 'cui', '钟': 'zhong', '谭': 'tan', '陆': 'lu', '汪': 'wang',
  '范': 'fan', '石': 'shi', '廖': 'liao', '贾': 'jia', '夏': 'xia',
  '韦': 'wei', '付': 'fu', '方': 'fang', '白': 'bai', '邹': 'zou',
  '孟': 'meng', '熊': 'xiong', '秦': 'qin', '邱': 'qiu', '江': 'jiang',
  '尹': 'yin', '薛': 'xue', '闫': 'yan', '段': 'duan', '雷': 'lei',
  '侯': 'hou', '龙': 'long', '史': 'shi', '陶': 'tao', '黎': 'li',
  '贺': 'he', '顾': 'gu', '毛': 'mao', '郝': 'hao', '龚': 'gong',
  '邵': 'shao', '万': 'wan', '钱': 'qian', '严': 'yan', '覃': 'qin',
  '武': 'wu', '戴': 'dai', '莫': 'mo', '孔': 'kong', '向': 'xiang',
  '汤': 'tang', '温': 'wen', '康': 'kang', '施': 'shi', '文': 'wen',
  '牛': 'niu', '樊': 'fan', '葛': 'ge', '邢': 'xing', '安': 'an',
  '齐': 'qi', '易': 'yi', '乔': 'qiao', '伍': 'wu', '庞': 'pang',
  '颜': 'yan', '倪': 'ni', '庄': 'zhuang', '聂': 'nie', '章': 'zhang',
  '岳': 'yue', '鲁': 'lu', '翟': 'zhai', '殷': 'yin', '詹': 'zhan',
  '申': 'shen', '欧': 'ou', '耿': 'geng', '关': 'guan', '兰': 'lan',
  '焦': 'jiao', '俞': 'yu', '左': 'zuo', '柳': 'liu', '甘': 'gan',
  '祝': 'zhu', '包': 'bao', '宁': 'ning', '尚': 'shang', '符': 'fu',

  // === 常见名字用字 ===
  '伟': 'wei', '芳': 'fang', '娜': 'na', '敏': 'min', '静': 'jing',
  '丽': 'li', '强': 'qiang', '磊': 'lei', '洋': 'yang', '勇': 'yong',
  '艳': 'yan', '杰': 'jie', '娟': 'juan', '涛': 'tao', '明': 'ming',
  '超': 'chao', '秀': 'xiu', '霞': 'xia', '平': 'ping', '玲': 'ling',
  '刚': 'gang', '华': 'hua', '桂': 'gui', '飞': 'fei', '鑫': 'xin',
  '鹏': 'peng', '宇': 'yu', '浩': 'hao', '然': 'ran', '博': 'bo',
  '文': 'wen', '辉': 'hui', '斌': 'bin', '峰': 'feng', '晨': 'chen',
  '睿': 'rui', '轩': 'xuan', '铭': 'ming', '志': 'zhi', '龙': 'long',
  '成': 'cheng', '达': 'da', '翔': 'xiang', '凯': 'kai', '瑞': 'rui',
  '佳': 'jia', '怡': 'yi', '雪': 'xue', '慧': 'hui', '婷': 'ting',

  // === 补充常用字 ===
  '一': 'yi', '二': 'er', '四': 'si', '五': 'wu', '六': 'liu',
  '七': 'qi', '八': 'ba', '九': 'jiu', '十': 'shi', '百': 'bai',
  '千': 'qian', '万': 'wan', '亿': 'yi', '零': 'ling',
  '山': 'shan', '河': 'he', '湖': 'hu', '江': 'jiang', '桥': 'qiao',
  '楼': 'lou', '房': 'fang', '屋': 'wu', '家': 'jia', '居': 'ju',
  '人': 'ren', '民': 'min', '共': 'gong', '和': 'he', '党': 'dang',
  '军': 'jun', '警': 'jing', '察': 'cha', '法': 'fa', '律': 'lv',
  '知': 'zhi', '识': 'shi', '产': 'chan', '权': 'quan', '版': 'ban',
  '印': 'yin', '刷': 'shua', '出': 'chu', '入': 'ru', '门': 'men',
  '车': 'che', '火': 'huo', '飞': 'fei', '机': 'ji', '船': 'chuan',
  '光': 'guang', '亮': 'liang', '星': 'xing', '辰': 'chen', '宇': 'yu',
  '宙': 'zhou', '科': 'ke', '研': 'yan', '创': 'chuang', '造': 'zao',
  '世': 'shi', '界': 'jie', '未': 'wei', '来': 'lai', '现': 'xian',
  '在': 'zai', '过': 'guo', '去': 'qu', '将': 'jiang', '永': 'yong',
  '远': 'yuan', '前': 'qian', '后': 'hou', '左': 'zuo', '右': 'you',
  '上': 'shang', '下': 'xia', '内': 'nei', '外': 'wai', '正': 'zheng',
  '反': 'fan', '高': 'gao', '低': 'di', '多': 'duo', '少': 'shao',
  '快': 'kuai', '慢': 'man', '早': 'zao', '晚': 'wan', '今': 'jin',
  '昨': 'zuo', '年': 'nian', '月': 'yue', '时': 'shi', '间': 'jian',
  '春': 'chun', '夏': 'xia', '秋': 'qiu', '冬': 'dong', '季': 'ji',
  '风': 'feng', '雨': 'yu', '雷': 'lei', '雪': 'xue', '冰': 'bing',
  '花': 'hua', '草': 'cao', '树': 'shu', '竹': 'zhu', '松': 'song',
  '梅': 'mei', '兰': 'lan', '菊': 'ju', '荷': 'he', '莲': 'lian',
  '红': 'hong', '橙': 'cheng', '绿': 'lv', '蓝': 'lan', '紫': 'zi',
  '黑': 'hei', '白': 'bai', '灰': 'hui', '金': 'jin', '银': 'yin',
  '铜': 'tong', '铁': 'tie', '钢': 'gang', '锡': 'xi', '铅': 'qian',
  '元': 'yuan', '角': 'jiao', '圆': 'yuan', '方': 'fang', '长': 'chang',
  '短': 'duan', '粗': 'cu', '细': 'xi', '厚': 'hou', '薄': 'bao',
  '真': 'zhen', '假': 'jia', '善': 'shan', '恶': 'e', '美': 'mei',
  '丑': 'chou', '爱': 'ai', '恨': 'hen', '喜': 'xi', '怒': 'nu',
  '哀': 'ai', '乐': 'le', '忧': 'you', '愁': 'chou', '思': 'si',
  '想': 'xiang', '念': 'nian', '记': 'ji', '忘': 'wang', '梦': 'meng',
  '学': 'xue', '问': 'wen', '答': 'da', '题': 'ti', '考': 'kao',
  '试': 'shi', '练': 'lian', '习': 'xi', '复': 'fu', '预': 'yu',
  '胜': 'sheng', '败': 'bai', '赢': 'ying', '输': 'shu', '战': 'zhan',
  '斗': 'dou', '争': 'zheng', '夺': 'duo', '取': 'qu', '给': 'gei',
  '送': 'song', '收': 'shou', '买': 'mai', '卖': 'mai', '购': 'gou',
  '销': 'xiao', '售': 'shou', '租': 'zu', '借': 'jie', '贷': 'dai',
  '存': 'cun', '储': 'chu', '汇': 'hui', '兑': 'dui', '付': 'fu',
  '款': 'kuan', '账': 'zhang', '户': 'hu', '卡': 'ka', '密': 'mi',
  '码': 'ma', '签': 'qian', '证': 'zheng', '牌': 'pai', '执': 'zhi',
  '照': 'zhao', '票': 'piao', '单': 'dan', '报': 'bao', '表': 'biao',
  '格': 'ge', '册': 'ce', '簿': 'bu', '纸': 'zhi', '笔': 'bi',
  '墨': 'mo', '书': 'shu', '画': 'hua', '图': 'tu', '像': 'xiang',
  '声': 'sheng', '色': 'se', '味': 'wei', '香': 'xiang', '甜': 'tian',
  '苦': 'ku', '辣': 'la', '咸': 'xian', '酸': 'suan', '淡': 'dan',
  '吃': 'chi', '喝': 'he', '饭': 'fan', '菜': 'cai', '肉': 'rou',
  '米': 'mi', '面': 'mian', '糖': 'tang', '盐': 'yan', '酒': 'jiu',
  '茶': 'cha', '烟': 'yan', '果': 'guo', '蔬': 'shu', '蛋': 'dan',
  '奶': 'nai', '鱼': 'yu', '虾': 'xia', '蟹': 'xie', '贝': 'bei',
  '猫': 'mao', '狗': 'gou', '猪': 'zhu', '牛': 'niu', '羊': 'yang',
  '马': 'ma', '鸡': 'ji', '鸭': 'ya', '鹅': 'e', '鸟': 'niao',
  '虫': 'chong', '蛇': 'she', '龙': 'long', '凤': 'feng', '虎': 'hu',
  '狮': 'shi', '豹': 'bao', '狼': 'lang', '狐': 'hu', '兔': 'tu',
  '新': 'xin', '旧': 'jiu', '古': 'gu', '老': 'lao', '少': 'shao',
  '男': 'nan', '女': 'nv', '父': 'fu', '母': 'mu', '儿': 'er',
  '兄': 'xiong', '弟': 'di', '姐': 'jie', '妹': 'mei', '夫': 'fu',
  '妻': 'qi', '朋': 'peng', '友': 'you', '邻': 'lin', '客': 'ke',
  '主': 'zhu', '宾': 'bin', '师': 'shi', '徒': 'tu', '官': 'guan',
  '兵': 'bing', '将': 'jiang', '帅': 'shuai', '帝': 'di', '王': 'wang',
  '皇': 'huang', '圣': 'sheng', '神': 'shen', '仙': 'xian', '佛': 'fo',
  '鬼': 'gui', '妖': 'yao', '魔': 'mo', '怪': 'guai', '精': 'jing',
  '灵': 'ling', '魂': 'hun', '魄': 'po', '命': 'ming', '运': 'yun',
  '福': 'fu', '禄': 'lu', '寿': 'shou', '喜': 'xi', '吉': 'ji',
  '祥': 'xiang', '如': 'ru', '意': 'yi', '财': 'cai', '富': 'fu',
  '安': 'an', '康': 'kang', '健': 'jian', '宁': 'ning', '平': 'ping',
  '和': 'he', '顺': 'shun', '昌': 'chang', '盛': 'sheng', '兴': 'xing',
  '隆': 'long', '旺': 'wang', '发': 'fa', '达': 'da', '通': 'tong',
  '泰': 'tai', '宏': 'hong', '博': 'bo', '雅': 'ya', '睿': 'rui',
  '智': 'zhi', '诚': 'cheng', '信': 'xin', '仁': 'ren', '义': 'yi',
  '礼': 'li', '孝': 'xiao', '忠': 'zhong', '勇': 'yong', '毅': 'yi',
  '恒': 'heng', '勤': 'qin', '俭': 'jian', '廉': 'lian', '洁': 'jie',
  '清': 'qing', '正': 'zheng', '直': 'zhi', '公': 'gong', '道': 'dao',
  '德': 'de', '品': 'pin', '质': 'zhi', '格': 'ge', '性': 'xing',
  '情': 'qing', '感': 'gan', '恩': 'en', '怨': 'yuan', '仇': 'chou',
  '战': 'zhan', '攻': 'gong', '守': 'shou', '进': 'jin', '退': 'tui',
  '增': 'zeng', '减': 'jian', '加': 'jia', '除': 'chu', '乘': 'cheng',
  '倍': 'bei', '半': 'ban', '双': 'shuang', '单': 'dan', '独': 'du',
  '孤': 'gu', '寡': 'gua', '众': 'zhong', '群': 'qun', '队': 'dui',
  '组': 'zu', '班': 'ban', '级': 'ji', '阶': 'jie', '层': 'ceng',
  '等': 'deng', '级': 'ji', '优': 'you', '秀': 'xiu', '良': 'liang',
  '差': 'cha', '劣': 'lie', '好': 'hao', '坏': 'huai',
  '校': 'xiao', '园': 'yuan', '课': 'ke', '堂': 'tang', '讲': 'jiang',
  '授': 'shou', '培': 'pei', '训': 'xun', '辅': 'fu', '导': 'dao',
  '图': 'tu', '馆': 'guan', '实': 'shi', '验': 'yan', '室': 'shi',
  '宿': 'su', '舍': 'she', '食': 'shi', '堂': 'tang', '操': 'cao',
  '场': 'chang', '运': 'yun', '赛': 'sai', '比': 'bi', '竞': 'jing',
  '冠': 'guan', '杯': 'bei', '奖': 'jiang', '牌': 'pai', '旗': 'qi',
  '歌': 'ge', '舞': 'wu', '戏': 'xi', '剧': 'ju', '曲': 'qu',
  '弹': 'tan', '唱': 'chang', '演': 'yan', '奏': 'zou', '画': 'hua',
  '写': 'xie', '读': 'du', '看': 'kan', '听': 'ting', '说': 'shuo',
  '讲': 'jiang', '谈': 'tan', '聊': 'liao', '议': 'yi', '论': 'lun',
  '辩': 'bian', '驳': 'bo', '证': 'zheng', '明': 'ming', '显': 'xian',
  '隐': 'yin', '藏': 'cang', '露': 'lu', '现': 'xian', '示': 'shi',
  '暗': 'an', '亮': 'liang', '黑': 'hei', '白': 'bai', '彩': 'cai',
  '素': 'su', '艳': 'yan', '丽': 'li', '华': 'hua', '朴': 'pu',
  '简': 'jian', '繁': 'fan', '杂': 'za', '乱': 'luan', '整': 'zheng',
  '洁': 'jie', '净': 'jing', '脏': 'zang', '干': 'gan', '湿': 'shi',
  '潮': 'chao', '燥': 'zao', '润': 'run', '滑': 'hua', '涩': 'se',
  '软': 'ruan', '硬': 'ying', '轻': 'qing', '弹': 'tan', '韧': 'ren',
  '脆': 'cui', '坚': 'jian', '固': 'gu', '牢': 'lao', '松': 'song',
  '紧': 'jin', '宽': 'kuan', '窄': 'zhai', '狭': 'xia', '阔': 'kuo',
  '丰': 'feng', '盛': 'sheng', '茂': 'mao', '荒': 'huang', '芜': 'wu',
  '荣': 'rong', '枯': 'ku', '衰': 'shuai', '旺': 'wang', '兴': 'xing',
  '废': 'fei', '存': 'cun', '亡': 'wang', '生': 'sheng', '死': 'si',
  '活': 'huo', '动': 'dong', '静': 'jing', '止': 'zhi', '停': 'ting',
  '始': 'shi', '终': 'zhong', '毕': 'bi', '完': 'wan', '成': 'cheng',
  '功': 'gong', '失': 'shi', '败': 'bai', '得': 'de', '损': 'sun',
  '益': 'yi', '弊': 'bi', '优': 'you', '缺': 'que', '点': 'dian',
  '涨': 'zhang', '跌': 'die', '升': 'sheng', '降': 'jiang', '浮': 'fu',
  '飘': 'piao', '荡': 'dang', '摇': 'yao', '摆': 'bai', '晃': 'huang',
  '转': 'zhuan', '旋': 'xuan', '绕': 'rao', '围': 'wei', '包': 'bao',
  '裹': 'guo', '封': 'feng', '闭': 'bi', '启': 'qi', '揭': 'jie',
  '撕': 'si', '裂': 'lie', '破': 'po', '碎': 'sui', '断': 'duan',
  '折': 'zhe', '弯': 'wan', '曲': 'qu', '扭': 'niu', '拐': 'guai',
  '直': 'zhi', '斜': 'xie', '横': 'heng', '竖': 'shu', '纵': 'zong',
  '穿': 'chuan', '插': 'cha', '刺': 'ci', '扎': 'zha', '切': 'qie',
  '割': 'ge', '砍': 'kan', '劈': 'pi', '削': 'xiao', '刮': 'gua',
  '挖': 'wa', '掘': 'jue', '填': 'tian', '埋': 'mai', '堆': 'dui',
  '积': 'ji', '累': 'lei', '叠': 'die', '摞': 'luo', '码': 'ma',
  '排': 'pai', '列': 'lie', '序': 'xu', '秩': 'zhi', '次': 'ci',
  '第': 'di', '首': 'shou', '尾': 'wei', '头': 'tou', '顶': 'ding',
  '底': 'di', '基': 'ji', '础': 'chu', '根': 'gen', '本': 'ben',
  '末': 'mo', '梢': 'shao', '尖': 'jian', '端': 'duan', '边': 'bian',
  '缘': 'yuan', '沿': 'yan', '靠': 'kao', '近': 'jin', '贴': 'tie',
  '邻': 'lin', '隔': 'ge', '离': 'li', '距': 'ju', '差': 'cha',
  '距': 'ju', '远': 'yuan', '遥': 'yao', '迈': 'mai', '跨': 'kua',
  '越': 'yue', '超': 'chao', '追': 'zhui', '赶': 'gan', '跟': 'gen',
  '随': 'sui', '陪': 'pei', '伴': 'ban', '携': 'xie', '带': 'dai',
  '拿': 'na', '握': 'wo', '抓': 'zhua', '捉': 'zhuo', '捕': 'bu',
  '捞': 'lao', '捡': 'jian', '拾': 'shi', '扔': 'reng', '抛': 'pao',
  '投': 'tou', '掷': 'zhi', '射': 'she', '击': 'ji', '打': 'da',
  '砸': 'za', '敲': 'qiao', '拍': 'pai', '捶': 'chui', '捣': 'dao',
  '搅': 'jiao', '拌': 'ban', '混': 'hun', '合': 'he', '融': 'rong',
  '化': 'hua', '溶': 'rong', '解': 'jie', '析': 'xi', '分': 'fen',
  '辨': 'bian', '认': 'ren', '识': 'shi', '懂': 'dong', '晓': 'xiao',
  '悉': 'xi', '熟': 'shu', '练': 'lian', '巧': 'qiao', '笨': 'ben',
  '拙': 'zhuo', '愚': 'yu', '蠢': 'chun', '聪': 'cong', '慧': 'hui',
  '敏': 'min', '捷': 'jie', '锐': 'rui', '钝': 'dun', '锋': 'feng',
  '利': 'li', '刃': 'ren', '刀': 'dao', '剑': 'jian', '枪': 'qiang',
  '棍': 'gun', '棒': 'bang', '鞭': 'bian', '绳': 'sheng', '索': 'suo',
  '链': 'lian', '环': 'huan', '圈': 'quan', '套': 'tao', '笼': 'long',
  '箱': 'xiang', '盒': 'he', '袋': 'dai', '包': 'bao', '囊': 'nang',
  '碗': 'wan', '盘': 'pan', '碟': 'die', '杯': 'bei', '瓶': 'ping',
  '罐': 'guan', '壶': 'hu', '锅': 'guo', '灶': 'zao', '炉': 'lu',
  '柜': 'gui', '橱': 'chu', '桌': 'zhuo', '椅': 'yi', '凳': 'deng',
  '床': 'chuang', '枕': 'zhen', '被': 'bei', '褥': 'ru', '帘': 'lian',
  '窗': 'chuang', '镜': 'jing', '梳': 'shu', '刷': 'shua', '扫': 'sao',
  '拖': 'tuo', '擦': 'ca', '抹': 'ma', '洗': 'xi', '涤': 'di',
  '冲': 'chong', '泼': 'po', '洒': 'sa', '浇': 'jiao', '灌': 'guan',
  '涌': 'yong', '喷': 'pen', '流': 'liu', '淌': 'tang', '滴': 'di',
  '漏': 'lou', '渗': 'shen', '浸': 'jin', '泡': 'pao', '淹': 'yan',
  '没': 'mei', '沉': 'chen', '浮': 'fu', '漂': 'piao', '游': 'you',
  '泳': 'yong', '潜': 'qian', '涉': 'she', '渡': 'du', '过': 'guo',
  '遇': 'yu', '逢': 'feng', '遭': 'zao', '受': 'shou', '承': 'cheng',
  '担': 'dan', '负': 'fu', '责': 'ze', '任': 'ren', '义': 'yi',
  '务': 'wu', '职': 'zhi', '位': 'wei', '岗': 'gang', '轮': 'lun',
  '值': 'zhi', '换': 'huan', '替': 'ti', '代': 'dai', '顶': 'ding',
  '冒': 'mao', '充': 'chong', '假': 'jia', '伪': 'wei', '虚': 'xu',
  '装': 'zhuang', '扮': 'ban', '演': 'yan', '饰': 'shi', '妆': 'zhuang',
  '戴': 'dai', '披': 'pi', '挂': 'gua', '悬': 'xuan', '吊': 'diao',
  '垂': 'chui', '落': 'luo', '坠': 'zhui', '掉': 'diao', '跌': 'die',
  '倒': 'dao', '倾': 'qing', '覆': 'fu', '翻': 'fan', '滚': 'gun',
  '爬': 'pa', '攀': 'pan', '登': 'deng', '跪': 'gui', '蹲': 'dun',
  '站': 'zhan', '立': 'li', '坐': 'zuo', '卧': 'wo', '躺': 'tang',
  '靠': 'kao', '倚': 'yi', '扶': 'fu', '撑': 'cheng', '托': 'tuo',
  '举': 'ju', '抬': 'tai', '搬': 'ban', '运': 'yun', '输': 'shu',
  '载': 'zai', '装': 'zhuang', '卸': 'xie', '堆': 'dui', '码': 'ma',
  '存': 'cun', '放': 'fang', '置': 'zhi', '摆': 'bai', '设': 'she',
  '布': 'bu', '局': 'ju', '排': 'pai', '编': 'bian', '织': 'zhi',
  '缝': 'feng', '绣': 'xiu', '染': 'ran', '绘': 'hui', '漆': 'qi',
  '涂': 'tu', '喷': 'pen', '镀': 'du', '铸': 'zhu', '锻': 'duan',
  '焊': 'han', '铆': 'mao', '钉': 'ding', '栓': 'shuan', '螺': 'luo',
  '母': 'mu', '齿': 'chi', '轴': 'zhou', '承': 'cheng', '阀': 'fa',
  '泵': 'beng', '缸': 'gang', '筒': 'tong', '管': 'guan', '杆': 'gan',
  '梁': 'liang', '柱': 'zhu', '板': 'ban', '块': 'kuai', '条': 'tiao',
  '丝': 'si', '线': 'xian', '纱': 'sha', '棉': 'mian', '麻': 'ma',
  '毛': 'mao', '皮': 'pi', '革': 'ge', '塑': 'su', '橡': 'xiang',
  '胶': 'jiao', '玻': 'bo', '璃': 'li', '陶': 'tao', '瓷': 'ci',
  '砖': 'zhuan', '瓦': 'wa', '沙': 'sha', '泥': 'ni', '灰': 'hui',
  '尘': 'chen', '土': 'tu', '壤': 'rang', '田': 'tian', '耕': 'geng',
  '种': 'zhong', '植': 'zhi', '播': 'bo', '收': 'shou', '割': 'ge',
  '获': 'huo', '粮': 'liang', '棉': 'mian', '蔬': 'shu', '养': 'yang',
  '殖': 'zhi', '畜': 'chu', '禽': 'qin', '兽': 'shou', '宠': 'chong',
  '英': 'ying', '语': 'yu', '数': 'shu', '据': 'ju', '库': 'ku',
  // === 补充常见互联网/品牌用字 ===
  '度': 'du', '阿': 'a', '里': 'li', '巴': 'ba', '腾': 'teng', '为': 'wei',
  '字': 'zi', '节': 'jie', '跳': 'tiao', '搜': 'sou', '浪': 'lang',
  '狐': 'hu', '携': 'xie', '滴': 'di', '迪': 'di', '克': 'ke',
  '斯': 'si', '朗': 'lang', '普': 'pu', '奥': 'ao', '拜': 'bai',
  '互': 'hu', '微': 'wei', '谷': 'gu', '苹': 'ping', '逊': 'xun',
  '脸': 'lian', '谱': 'pu', '推': 'tui', '软': 'ruan', '歌': 'ge',
  '亚': 'ya', '逊': 'xun', '讯': 'xun',
};

// 默认常见后缀
const DEFAULT_SUFFIXES = [
  '123',
  '1234',
  '12345',
  '123456',
  '1234567',
  '12345678',
  '123456789',
  '1234567890',
  '123456!',
  '123456@',
  '123456#',
  '123456$',
  '123qwe',
  '123qwe!@#',
  '123qweASD',
  'qwe123',
  'qweasd',
  'qwerty',
  'qwerty123',
  'password',
  'password123',
  'admin',
  'admin123',
  'admin888',
  'admin@123',
  'root',
  'root123',
  'root@123',
  'test',
  'test123',
  'abc123',
  'abc123456',
  'abcd1234',
  'a123456',
  'a123456789',
  '111111',
  '666666',
  '888888',
  '88888888',
  '000000',
  '11111111',
  '1qaz2wsx',
  '1q2w3e4r',
  '1q2w3e4r5t',
  '!@#$%^&*',
  '!@#123',
  '@#￥%',
  'passw0rd',
  'P@ssw0rd',
  'p@ssw0rd',
  'iloveyou',
  'hello',
  'hello123',
  'welcome',
  'welcome123',
  'letmein',
  'monkey',
  'dragon',
  'master',
  'login',
  'abc123!@#',
  'zxcvbnm',
  'asdfgh',
  'asdfghjkl',
  'qazwsx',
  '!QAZ2wsx',
  'zaq12wsx',
  'P@$$w0rd',
  'Admin@123',
  'admin@123',
  'Root@123',
  'Test@123',
  'User@123',
];

// 无分隔符后缀（规则2：{data}YYYY, {data}123 等直接拼接）
const DEFAULT_NO_SEP_SUFFIXES = [
  '2010','2011','2012','2013','2014','2015','2016','2017','2018','2019',
  '2020','2021','2022','2023','2024','2025','2026',
  '123','123456','12345678',
  '888','888888',
  '666','666666',
  '111','111111',
  '000','000000',
];

// 常见企业账号前缀（规则4：admin@{data} 等）
const DEFAULT_ACCOUNT_PREFIXES = [
  'admin','root','sa','test','user','guest','manager','system','oracle','mysql',
];

// 企业常见默认后缀（规则6：{data}@123.com 等，含自带分隔符）
const DEFAULT_ENTERPRISE_SUFFIXES = [
  '@123.com','@qq.com','@163.com','@gmail.com','@139.com','@sina.com','@126.com',
  '@hotmail.com','@outlook.com','@yahoo.com','@sohu.com','@foxmail.com',
  '#123','@pwd','pwd','pass','@pass','passwd',
];

// 转拼音（支持多音字简单处理，取第一个音）
function toPinyin(text) {
  let result = '';
  for (const ch of text) {
    const py = PINYIN_MAP[ch];
    if (py) {
      result += py;
    } else if (/[一-鿿]/.test(ch)) {
      // 不认识的汉字保留原字（但这种情况应该很少）
      result += ch;
    } else {
      result += ch;
    }
  }
  return result;
}

// 判断是否包含中文
function hasChinese(text) {
  return /[一-鿿]/.test(text);
}

// 首字母大写
function capitalize(str) {
  if (!str) return str;
  return str.charAt(0).toUpperCase() + str.slice(1);
}
